import {
  Blocks,
  Briefcase,
  Building2,
  Car,
  CarTaxiFront,
  Clapperboard,
  Code2,
  GraduationCap,
  HeartPulse,
  LayoutGrid,
  MessagesSquare,
  Newspaper,
  PawPrint,
  Palette,
  PiggyBank,
  Plane,
  Repeat2,
  Shirt,
  ShoppingCart,
  Sofa,
  Sparkles,
  Ticket,
  TrendingUp,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react';

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  dev: Code2,
  community: MessagesSquare,
  'fashion-beauty': Shirt,
  'living-shopping': Sofa,
  grocery: ShoppingCart,
  'food-delivery': UtensilsCrossed,
  secondhand: Repeat2,
  mobility: CarTaxiFront,
  finance: PiggyBank,
  'news-media': Newspaper,
  investment: TrendingUp,
  hobby: Palette,
  travel: Plane,
  culture: Clapperboard,
  ticket: Ticket,
  productivity: LayoutGrid,
  career: Briefcase,
  edu: GraduationCap,
  'living-service': Sparkles,
  pet: PawPrint,
  'real-estate': Building2,
  auto: Car,
  health: HeartPulse,
  'figure-toy': Blocks,
};

export function getDiscoverCategoryIcon(categorySlug: string): LucideIcon {
  return CATEGORY_ICONS[categorySlug] ?? Sparkles;
}
