import {
  Blocks,
  Briefcase,
  Building2,
  Car,
  CarTaxiFront,
  Clapperboard,
  Code2,
  Dumbbell,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Keyboard,
  Languages,
  LayoutGrid,
  MessagesSquare,
  Music2,
  Newspaper,
  PawPrint,
  Palette,
  PiggyBank,
  Plane,
  Repeat2,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Sofa,
  Sparkles,
  Star,
  Tent,
  Ticket,
  TrendingUp,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react';

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  dev: Code2,
  community: MessagesSquare,
  'fashion-beauty': Shirt,
  'living-shopping': Sofa,
  grocery: ShoppingCart,
  'food-delivery': UtensilsCrossed,
  secondhand: Repeat2,
  mobility: CarTaxiFront,
  finance: PiggyBank,
  'news-media': Newspaper,
  investment: TrendingUp,
  hobby: Palette,
  travel: Plane,
  culture: Clapperboard,
  ticket: Ticket,
  productivity: LayoutGrid,
  career: Briefcase,
  edu: GraduationCap,
  'living-service': Sparkles,
  pet: PawPrint,
  'real-estate': Building2,
  auto: Car,
  health: HeartPulse,
  'figure-toy': Blocks,
  'open-market': ShoppingCart,
  insurance: ShieldCheck,
  dating: Heart,
  'part-time-gig': Briefcase,
  'kpop-fandom': Music2,
  'restaurant-reservation': UtensilsCrossed,
  'review-campaign': Star,
  'beauty-clinic': Sparkles,
  'gaming-esports': Gamepad2,
  fitness: Dumbbell,
  'language-learning': Languages,
  'camping-outdoor': Tent,
  'custom-keyboard': Keyboard,
  'pet-figure': Gift,
};

export function getDiscoverCategoryIcon(categorySlug: string): LucideIcon {
  return CATEGORY_ICONS[categorySlug] ?? Sparkles;
}
